version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: GDtest
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring_app
    environment:
      DB_HOST: db:5432
      DB_NAME: GDtest
      DB_USER: root
      DB_USER_PASSWORD: 123
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: